RRAID = [
    "𝗕𝗜𝗛𝗔𝗥𝗜  𝗣𝗔𝗣𝗔  𝗛𝗔𝗜  𝗧𝗘𝗥𝗘  𝗛𝗔𝗠",
    "𝗕𝗜𝗛𝗔𝗥𝗜 𝗞𝗔 𝗕𝗘𝗧𝗔 𝗧𝗨 𝗟𝗔𝗗𝗘𝗚𝗔 𝗕𝗜𝗛𝗔𝗥𝗜𝗢 𝗦𝗘",
    "𝗔𝗔𝗥𝗘 𝗕𝗘𝗧𝗔 𝗧𝗢𝗛𝗔𝗥 𝗠𝗔𝗜 𝗞𝗘 𝗖𝗛𝗢𝗢𝗖𝗛𝗜 𝗗𝗔𝗕𝗔𝗔𝗔𝗪𝗘𝗘 𝗗𝗘𝗘",
    "𝗥𝗔𝗡𝗗𝗜 𝗞𝗘 𝗕𝗔𝗖𝗛𝗔 𝗕𝗔𝗥𝗘 𝗧𝗨 𝗠𝗔𝗗𝗛𝗔𝗥𝗫𝗛𝗢𝗗𝗗",
    "𝗧𝗢𝗛𝗔𝗥 𝗕𝗔𝗛𝗜𝗡 𝗞𝗘 𝗕𝗢𝗢𝗥 𝗖𝗛𝗢𝗗𝗗 𝗗𝗘𝗕𝗕",
    "𝗧𝗢𝗛𝗔𝗥 𝗡𝗔𝗡𝗜 𝗞𝗘 𝗚𝗔𝗡𝗗 𝗠𝗘 𝗠𝗢𝗧 𝗠𝗢𝗧 𝗛𝗔𝗧𝗛 𝗞𝗘 𝗟𝗨𝗡𝗗 𝗚𝗛𝗨𝗦𝗪𝗔 𝗗𝗘𝗕",
    "𝗧𝗢𝗛𝗔𝗥 𝗕𝗔𝗛𝗜𝗡 𝗞𝗘 𝗖𝗛𝗢𝗢𝗢𝗢𝗧𝗧𝗧 𝗞𝗔𝗔𝗧𝗧 𝗞𝗘𝗘 𝗪𝗢𝗠𝗘 𝗡𝗔𝗠𝗔𝗞𝗞𝗞 𝗗𝗔𝗔𝗟𝗟 𝗗𝗘𝗕𝗕𝗕",
    "𝗧𝗢𝗛𝗔𝗥 𝗕𝗔𝗛𝗜𝗡 𝗞𝗘 𝗖𝗛𝗢𝗗 𝗖𝗛𝗢𝗗 𝗞𝗘 𝗧𝗢𝗛𝗞𝗘 𝗠𝗔𝗠𝗔 𝗕𝗔𝗡𝗔𝗔 𝗗𝗘𝗕𝗕",
    "𝗧𝗢𝗛𝗔𝗥 𝗕𝗔𝗛𝗜𝗡 𝗞𝗘 𝗕𝗢𝗢𝗥𝗥 𝗠𝗘 𝗟𝗨𝗡𝗗 𝗛𝗔𝗠𝗔𝗥 𝗝𝗔𝗔𝗔𝗜 𝗔𝗔𝗝",
    "𝗢𝗬𝗘 𝗠𝗔𝗗𝗛𝗔𝗙𝗖𝗛𝗢𝗗 𝗧𝗢𝗛𝗔𝗥 𝗠𝗔𝗜 𝗞𝗘 𝗦𝗔𝗧𝗕 𝗝𝗔𝗬𝗔𝗕 𝗛𝗔𝗠 𝗢𝗬𝗢",
    "𝗟𝗨𝗡𝗗𝗗 𝗟𝗘 𝗟𝗘 𝗠𝗔𝗗𝗛𝗔𝗥𝗫𝗛𝗢𝗗𝗗 𝗖𝗛𝗛𝗞𝗞𝗔 𝗕𝗔𝗥𝗘 𝗧𝗨 ",
    "𝗢𝗬𝗘 𝗦𝗨𝗡 𝗡 𝗧𝗢𝗛𝗔𝗥 𝗠𝗔𝗜 𝗠𝗘 𝗚𝗔𝗡𝗗 𝗢𝗬𝗢 𝗠𝗘 𝗖𝗛𝗢𝗗𝗗 𝗗𝗘𝗟𝗘 𝗕𝗔𝗡𝗜 𝗛𝗔𝗠",
    "𝗟𝗨𝗡𝗗 𝗞𝗘 𝗕𝗔𝗔𝗟 𝗕𝗔𝗥𝗘 𝗧𝗢𝗛𝗔𝗡𝗜 𝗞𝗘 𝗕𝗘𝗧𝗔 𝗞𝗘𝗧𝗡𝗢 𝗕𝗗𝗞𝗔 𝗛𝗢 𝗝𝗔𝗬𝗕𝗘 𝗟𝗘𝗞𝗜𝗡 𝗡𝗔𝗠𝗘 𝗝𝗛𝗔𝗧𝗧 𝗥𝗛𝗜 𝗧𝗢𝗛𝗔𝗥",
    "𝗔𝗡𝗗𝗜 𝗠𝗔𝗡𝗗𝗜 𝗦𝗔𝗡𝗗𝗜 𝗔𝗨𝗥 𝗧𝗢𝗛𝗔𝗥 𝗠𝗔𝗜 𝗦𝗔𝗦𝗧𝗜 𝗪𝗔𝗟𝗜 𝗥𝗔𝗡𝗗𝗜",
    "𝗧𝗢𝗛𝗔𝗥 𝗠𝗔𝗜 𝗞𝗘 𝗚𝗔𝗡𝗗 𝗠𝗘 𝗠𝗢𝗢𝗢𝗧 𝗗𝗘𝗕",
    "𝗕𝗘𝗧𝗪𝗔𝗔 𝗧𝗢𝗛𝗥𝗜 𝗠𝗔𝗜𝗬𝗔 𝗞𝗘 𝗕𝗢𝗢𝗥𝗥𝗪𝗔𝗔 𝗞𝗘 𝗖𝗛𝗨𝗗𝗔𝗔𝗜 𝗞𝗔𝗥𝗥𝗔𝗧𝗧 𝗕𝗔𝗡𝗜𝗜 𝗥𝗨𝗞𝗞 𝗧𝗨𝗨",
    "𝗠𝗔𝗔𝗗𝗛𝗔𝗥𝗖𝗛𝗢𝗢𝗗𝗗 𝗕𝗔𝗔𝗣 𝗦𝗘 𝗕𝗔𝗞𝗖𝗛𝗢𝗗𝗜 𝗞𝗔𝗥𝗕𝗘",
    "𝗧𝗢𝗛𝗔𝗥 𝗠𝗔𝗜 𝗞𝗘 𝗖𝗛𝗛𝗢𝗢𝗢𝗔𝗧𝗥𝗥𝗥𝗥 𝗞𝗔𝗧 𝗗𝗘𝗕𝗕",
    "𝗟𝗨𝗡𝗗𝗗 𝗟𝗘𝗘 𝗠𝗨𝗛𝗛 𝗠𝗘𝗘",
    "𝗠𝗔𝗔𝗔𝗜𝗜 𝗖𝗛𝗢𝗗𝗔𝗔𝗢𝗢 𝗧𝗨 𝗔𝗣𝗔𝗡  𝗝𝗔𝗔𝗞𝗘𝗘 ",
    "BIHARI PAPA HOTE H AND TERE BHI PAPA HAI",
    "MADHARCHODD TERIII MAA KO HAR EK BIHARI CHODEGA",
    "BIHAR WALE TERII MAA KO CHODD KE TUJHE PAIDA KIYE THE",
    "AAREE MADHARXHODD BIHARI PAPA BOL HME FASTTT",
    "BIHAR KE EK BACHA BHI TERI MA KO PREGNENT KRR DEGAA SMJHA",
    "JHATTU TU LADEGA BIHARI SE BIHARI AGR MUTH MAAR DEGA TO TU DAB KE MAR JAYEGA",
    "BIHAR KE CHHOTE CHHOTE BACHE TERE KHANDAN KO AKELA CHOD DEGA",
    "TOHRI MAIYA KE BOORRWA XHOFD KE PHAAR DEB SMJHLE MADHRCHOD",
    "TOHAR MAI RANDI BAA",
    "TOHRI BAHIN KE BOORR DILA DE BETA",
    "TOHARI AMAA KE GAND M LUND",
    "TOHAR MAAI KE BOORR CHODD DEB SALEE",
    "TOHARR BAAPP BAA BIHARII SMJHLEE MADHARCHODD",
    "AJAA LAUDAA LEE LEE BIHARII KEE AUR JALDI BOLL BIHARI PAPA",
    "TU RANDI KE PILEE BIHARI SE LADABEE TUU",
    "TOHARR MAAII KEE BOOR DEE DEE BET@ CHODD DEBB",
    "BIHARI KA LUND CHOOSEGA TABHI KAHI NHI JHUKEGAA",
    "SUN N RE MADHARCHODD BIHARI SE APAN MAI CHODWAA LE",
    "BIHARI KE BETA BIHARI KE HI GALI DET BAAA AB TA TOHAR MAI KE CHODAIAA HOTAU",
    "OYE BETWA TOHAR MAI HMRE SATH OYO JAAI AAJ",
    "HAMAR BETA TOHAR MAI KE BOORR ME LUND PEL DEB N TA ROYE LAGBE",
    "CHL AAO N RE MADHARCHODD LUND LE GAND ME",
    "TOHAR BAHINI KE BOORR KATT DEB",
    "JOR SE BOL BIHARI PAPA",
    "BOLBE JOR SE BIHARI PAPA KI TOHAR MAI KE GAND ME MOT MOT LUND PEL DI RE",
]


